package Main_system;

public enum ResponseType {
    PERSON_DOESNT_EXIST,
    PCR_WITH_ID_EXISTS,
    DISTRICT_DOESNT_EXIST,
    REGION_DOESNT_EXIST,
    WORKPLACE_DOESNT_EXIST,
    PCR_EXISTS_FOR_THAT_TIME,
    PCR_DOESNT_EXIST,
    LOWER_FROM_DATE,
    INCORRECT_PCR_FORMAT,
    PROBLEM_WITH_DELETING,
    SUCCESS
}
